model:
  onnx_model: ./lightstereo_s_sceneflow_general_opt_256_512_sim_conv.onnx
  
work_mode: PTQ


quant:
  activation:
    observer: KLDObserver
    dtype: int8
    symmetry: False
  
  weight:
    observer: KLDObserver
    dtype: int8
    symmetry: False
    per_channel: False

#automix:
#    bitwidth_list: [8,16]
#    algo: naive
    
dataset:
    calibrate:
      source: ./custom_loader.py
      target: custom_dataloader
      parameters:
        root: /share/datas/00000
        num_samples: 50
        
analysis_cfg:
   sim_compare:
   analysis_minmax: True
   analysis_percentile: True
   analysis_outlier: True
   analysis_save_histgram_path: ./compare_sim_his_out
   analysis_result_path:  ./compare_sim_out

out_dir: ./lightstereo_ptq_out




