#onnxsim lightstereo_s_sceneflow_general_opt_256_512.onnx lightstereo_s_sceneflow_general_opt_256_512_sim.onnx
OnnxConvertTool --input_model lightstereo_s_sceneflow_general_opt_256_512_sim.onnx --output_model lightstereo_s_sceneflow_general_opt_256_512_sim_conv.onnx
StatlasQuant --quant_cfg config_lightstereo_s_sceneflow_general_opt_256_512.yaml
mkdir stalas 
cd stalas
cp ../lightstereo_ptq_out/lightstereo_s_sceneflow_general_opt_256_512_sim_conv_deploy_model.onnx lightstereo_s_sceneflow_general_opt_256_512_sim_conv_deploy_model.onnx
cp ../lightstereo_ptq_out/lightstereo_s_sceneflow_general_opt_256_512_sim_conv_quant_param.yaml lightstereo_s_sceneflow_general_opt_256_512_sim_conv_quant_param.yaml
cp ../config_lightstereo.yaml config_lightstereo.yaml
/share/statlas/StatlasCompile -c config_lightstereo.yaml
